# Generated by Django 5.2 on 2025-05-03 01:59

import claimIT_backend.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimIT_backend', '0002_remove_userprofile_id_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=claimIT_backend.models.user_claim_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'gif', 'zip']), claimIT_backend.models.validate_document_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_documents', to='claimIT_backend.claim')),
            ],
        ),
    ]
