# Generated by Django 5.2 on 2025-05-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimIT_backend', '0003_claimdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
