# Generated by Django 5.2 on 2025-05-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimIT_backend', '0006_remove_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Fremont', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(default=94539, help_text='ZIP or postal code', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default='CA', help_text='State code (e.g., CA for California)', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='street_address',
            field=models.CharField(default='1234 Main Str.', help_text='Street address, apartment, unit, etc.', max_length=255),
            preserve_default=False,
        ),
    ]
