# Generated by Django 5.2 on 2025-05-05 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimIT_backend', '0007_alter_userprofile_city_alter_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disasterupdate',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='disasterupdate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='disasterupdate',
            name='description',
        ),
        migrations.AddField(
            model_name='disasterupdate',
            name='assistance_available',
            field=models.BooleanField(default=False, help_text='Whether any assistance programs are declared'),
        ),
        migrations.AddField(
            model_name='disasterupdate',
            name='declaration_type',
            field=models.CharField(blank=True, help_text='FEMA declaration type code (e.g., DR, FM, EM)', max_length=10),
        ),
        migrations.AddField(
            model_name='disasterupdate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last refresh date from FEMA'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disasterupdate',
            name='disaster_type',
            field=models.CharField(choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('hurricane', 'Hurricane'), ('tornado', 'Tornado'), ('wildfire', 'Wildfire'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='disasterupdate',
            name='location',
            field=models.CharField(help_text='Designated area affected by the disaster', max_length=255),
        ),
        migrations.AlterField(
            model_name='disasterupdate',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='disasterupdate',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
