# Generated by Django 5.2 on 2025-05-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimIT_backend', '0008_alter_disasterupdate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterupdate',
            name='declaration_display',
            field=models.CharField(blank=True, help_text='FEMA declaration display info', max_length=100),
        ),
    ]
