services:
  - type: web
    name: claimIT_backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn claimIT.wsgi --log-file -"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: claimIT.settings
      - key: DJANGO_SECRET_KEY
        fromEnv: DJANGO_SECRET_KEY
      - key: JWT_SECRET
        fromEnv: JWT_SECRET
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "claimit.onrender.com,localhost,127.0.0.1"
      - key: DB_NAME
        fromEnv: DB_NAME
      - key: DB_USER
        fromEnv: DB_USER
      - key: DB_PASSWORD
        fromEnv: DB_PASSWORD
      - key: DB_HOST
        fromEnv: DB_HOST
      - key: DB_PORT
        value: "5432"
      - key: CORS_ALLOWED_ORIGINS
        value: "http://localhost:3000"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://claimit.onrender.com"